services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env.development

  node:
    container_name: node
    build: 
    ports:
      - 5000:5000
    env_file:
      - .env.development
    depends_on:
      - postgres

volumes:
  postgres-volume: